.TH DECIBEL 1 "May 06, 2007"
.SH NAME
decibel-audio-player \- a simple audio player
.SH SYNOPSIS
.B decibel audio player
.SH DESCRIPTION
\fBDecibel\fP is an audio player that aims at being very straightforward to use. It makes use of the GStreamer library to read audio files.
.SH SEE ALSO
Homepage: http://decibel.silent-blade.org/
.SH AUTHOR
Decibel Audio Player was written by Ingelrest Francois <Francois.Ingelrest@gmail.com>
