.TH POGO 1 "September 16, 2010"
.SH NAME
pogo \- a simple audio player
.SH SYNOPSIS
.B pogo
.SH DESCRIPTION
\fBPogo\fP is probably the simplest and fastest audio player for Linux. 
Its elementary-inspired design uses the screen-space very efficiently. 
Pogo is especially well-suited for people who organize their music by 
albums on the harddrive. The main interface components are a directory 
tree and a playlist that groups albums in an innovative way.
.SH SEE ALSO
Homepage: http://launchpad.net/pogo
.SH AUTHOR
Pogo was written by Jendrik Seipp <jendrikseipp@web.de>.
It is a fork of Decibel Audio Player which was written by Ingelrest Francois <Francois.Ingelrest@gmail.com>.
