.TH POGO 1 "September 16, 2010"
.SH NAME
pogo \- a simple audio player
.SH SYNOPSIS
.B pogo
.SH DESCRIPTION
\fBPogo\fP is a fast and straightforward audio player. It uses innovative hierarchical playtrees instead of flat playlists. The GStreamer library is used to read audio files.
.SH SEE ALSO
Homepage: http://launchpad.net/pogo
.SH AUTHOR
Pogo was written by Jendrik Seipp <jendrikseipp@web.de>.
It is a fork of Decibel Audio Player which was written by Ingelrest Francois <Francois.Ingelrest@gmail.com>.
