.TH POGO-REMOTE "1" "September 16th 2010" "User Commands"
.SH NAME
pogo-remote \- Control Pogo remotely
.SH SYNOPSIS
.B Usage: pogo-remote command [arg1 arg2...]
.SH DESCRIPTION
\fBpogo-remote\fP allows you to control Pogo using DBus.

.SH OPTIONS
.TP
\fBnext\fR
Jump to the next track.
.TP
\fBpause\fR
Pause or continue playing the current track.
.TP
\fBpl\-add file1 file2...\fR
Append the given files to the playlist.
.TP
\fBpl\-clr\fR
Clear the playlist.
.TP
\fBpl\-set file1 file2...\fR
Set the playlist to the given files.
.TP
\fBplay\fR
Start playing the current track.
.TP
\fBprev\fR
Jump to the previous track.
.TP
\fBshuffle\fR
Shuffle the playlist.
.TP
\fBstop\fR
Stop playback.
.TP
\fBvolume value\fR
Change volume to value (0 -- 100).

.SH "SEE ALSO"
.B pogo(1)

.SH AUTHOR
Pogo was written by Jendrik Seipp <jendrikseipp@web.de>.
It is a fork of Decibel Audio Player which was written by Ingelrest Francois <athropos@gmail.com>.

This manual page was written mainly by Emilio Pozuelo Monfort <pochu@ubuntu.com>.
